export { PerfilSection } from './perfil';
export { ApplicationsSection } from './postulaciones/ApplicationsSection';
export { CvsSection } from './cvs';
export { SpacesSection } from './SpacesSection';
export { FeedbackSection } from './FeedbackSection';
export { EvidencesSection } from './EvidencesSection';
export { GoalsSection } from './GoalsSection';
export { PreparationSection } from './PreparationSection';
export { CvMatchSection } from './preparacion/CvMatchSection';
